### ISSUE TITLE
goodcheck will look into .git dirs when no glob

### ISSUE THREAD

**Issue by calancha** [sideci/goodcheck#20]
Let's suppose a user calls following command:
$ goodcheck check

And the user has a configuration file:
(Note: _Without_ glob)
```
rules:
  - id: com.example.foo
    pattern: foo
    message: Foo is Foo, not foo
    pass:
      - <a>Foo is Foo</a>
    fail:
      - <a>Foo is foo</a>
```

Since there is no glob, goodcheck will look all the files: including
those inside .git directories.

I rarely could imagine a user who wants goodcheck to look inside .git
directories.

I think this is a bit annoying for users.
For example, in my tests I am getting following reports:
.git/objects/33/5aab5489d48530130747e42cb14214475eebfb: #<ArgumentError: invalid byte sequence in UTF-8>
.git/objects/33/3d1d46a6961ef2bee034a440902496054d1aa8: #<ArgumentError: invalid byte sequence in UTF-8>
.git/objects/33/d0cffb67f821ef5eb2c52813f07c2dcb916f79: #<ArgumentError: invalid byte sequence in UTF-8>
.
.
.

Any idea?

* We could ignore dotfiles by default if the user provides neither files nor glob.
* Another way could be to have a .sideci_ignore file.
